package co.com.puj.aes.pagos.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "pagos")
public class Pagos {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idPagos;
    @DynamoDBAttribute
    private String razonSocial;
    @DynamoDBAttribute
    private String nombre;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String direccion;
    @DynamoDBAttribute
    private String teléfono;
    @DynamoDBAttribute
    private String pais;
    @DynamoDBAttribute
    private String contacto;
    @DynamoDBAttribute
    private String calificacion;
    @DynamoDBAttribute
    private boolean estado;
    @DynamoDBAttribute
    private String descripcion;


    public void setEstado(boolean b) {this.estado = b; }

    public void setIdPagos(String idPagos) { this.idPagos = idPagos; }
}
