//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceAvianca
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios.avianca.com/", ConfigurationName="ServiceReferenceAvianca.ServicioAviancaVuelos")]
    public interface ServicioAviancaVuelos
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.avianca.com//consultarVuelo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceAvianca.consultarVueloResponse> consultarVueloAsync(ServiceReferenceAvianca.consultarVueloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios.avianca.com//reservarVuelo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceAvianca.reservarVueloResponse> reservarVueloAsync(ServiceReferenceAvianca.reservarVueloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios.avianca.com/types/")]
    public partial class Vuelo
    {
        
        private System.Nullable<System.DateTime> fechaSalidaField;
        
        private System.Nullable<System.DateTime> fechaLlegadaField;
        
        private string ciudadOrigenField;
        
        private string vueloField;
        
        private string claseField;
        
        private string ciudadDestinoField;
        
        private System.Nullable<long> precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> fechaSalida
        {
            get
            {
                return this.fechaSalidaField;
            }
            set
            {
                this.fechaSalidaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> fechaLlegada
        {
            get
            {
                return this.fechaLlegadaField;
            }
            set
            {
                this.fechaLlegadaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ciudadOrigen
        {
            get
            {
                return this.ciudadOrigenField;
            }
            set
            {
                this.ciudadOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string vuelo
        {
            get
            {
                return this.vueloField;
            }
            set
            {
                this.vueloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string clase
        {
            get
            {
                return this.claseField;
            }
            set
            {
                this.claseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string ciudadDestino
        {
            get
            {
                return this.ciudadDestinoField;
            }
            set
            {
                this.ciudadDestinoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<long> precio
        {
            get
            {
                return this.precioField;
            }
            set
            {
                this.precioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarVueloElement", WrapperNamespace="http://servicios.avianca.com/types/", IsWrapped=true)]
    public partial class consultarVueloRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.avianca.com/types/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ciudadOrigen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.avianca.com/types/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ciudadDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.avianca.com/types/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> fechaSalida;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.avianca.com/types/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clase;
        
        public consultarVueloRequest()
        {
        }
        
        public consultarVueloRequest(string ciudadOrigen, string ciudadDestino, System.Nullable<System.DateTime> fechaSalida, string clase)
        {
            this.ciudadOrigen = ciudadOrigen;
            this.ciudadDestino = ciudadDestino;
            this.fechaSalida = fechaSalida;
            this.clase = clase;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarVueloResponseElement", WrapperNamespace="http://servicios.avianca.com/types/", IsWrapped=true)]
    public partial class consultarVueloResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.avianca.com/types/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public ServiceReferenceAvianca.Vuelo[] result;
        
        public consultarVueloResponse()
        {
        }
        
        public consultarVueloResponse(ServiceReferenceAvianca.Vuelo[] result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reservarVueloElement", WrapperNamespace="http://servicios.avianca.com/types/", IsWrapped=true)]
    public partial class reservarVueloRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.avianca.com/types/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceReferenceAvianca.Vuelo vuelo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.avianca.com/types/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nombrePasajero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.avianca.com/types/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> numeroIdentidadPasajero;
        
        public reservarVueloRequest()
        {
        }
        
        public reservarVueloRequest(ServiceReferenceAvianca.Vuelo vuelo, string nombrePasajero, System.Nullable<int> numeroIdentidadPasajero)
        {
            this.vuelo = vuelo;
            this.nombrePasajero = nombrePasajero;
            this.numeroIdentidadPasajero = numeroIdentidadPasajero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reservarVueloResponseElement", WrapperNamespace="http://servicios.avianca.com/types/", IsWrapped=true)]
    public partial class reservarVueloResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios.avianca.com/types/", Order=0)]
        public bool result;
        
        public reservarVueloResponse()
        {
        }
        
        public reservarVueloResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ServicioAviancaVuelosChannel : ServiceReferenceAvianca.ServicioAviancaVuelos, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServicioAviancaVuelosClient : System.ServiceModel.ClientBase<ServiceReferenceAvianca.ServicioAviancaVuelos>, ServiceReferenceAvianca.ServicioAviancaVuelos
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioAviancaVuelosClient() : 
                base(ServicioAviancaVuelosClient.GetDefaultBinding(), ServicioAviancaVuelosClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ServicioAviancaVuelosSoapHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAviancaVuelosClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioAviancaVuelosClient.GetBindingForEndpoint(endpointConfiguration), ServicioAviancaVuelosClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAviancaVuelosClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioAviancaVuelosClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAviancaVuelosClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioAviancaVuelosClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAviancaVuelosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceAvianca.consultarVueloResponse> ServiceReferenceAvianca.ServicioAviancaVuelos.consultarVueloAsync(ServiceReferenceAvianca.consultarVueloRequest request)
        {
            return base.Channel.consultarVueloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAvianca.consultarVueloResponse> consultarVueloAsync(string ciudadOrigen, string ciudadDestino, System.Nullable<System.DateTime> fechaSalida, string clase)
        {
            ServiceReferenceAvianca.consultarVueloRequest inValue = new ServiceReferenceAvianca.consultarVueloRequest();
            inValue.ciudadOrigen = ciudadOrigen;
            inValue.ciudadDestino = ciudadDestino;
            inValue.fechaSalida = fechaSalida;
            inValue.clase = clase;
            return ((ServiceReferenceAvianca.ServicioAviancaVuelos)(this)).consultarVueloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceAvianca.reservarVueloResponse> ServiceReferenceAvianca.ServicioAviancaVuelos.reservarVueloAsync(ServiceReferenceAvianca.reservarVueloRequest request)
        {
            return base.Channel.reservarVueloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAvianca.reservarVueloResponse> reservarVueloAsync(ServiceReferenceAvianca.Vuelo vuelo, string nombrePasajero, System.Nullable<int> numeroIdentidadPasajero)
        {
            ServiceReferenceAvianca.reservarVueloRequest inValue = new ServiceReferenceAvianca.reservarVueloRequest();
            inValue.vuelo = vuelo;
            inValue.nombrePasajero = nombrePasajero;
            inValue.numeroIdentidadPasajero = numeroIdentidadPasajero;
            return ((ServiceReferenceAvianca.ServicioAviancaVuelos)(this)).reservarVueloAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioAviancaVuelosSoapHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServicioAviancaVuelosSoapHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.100:8888/TuresBalonProviders-Avianca-context-root/ServicioAvianc" +
                        "aVuelosSoapHttpPort");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioAviancaVuelosClient.GetBindingForEndpoint(EndpointConfiguration.ServicioAviancaVuelosSoapHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioAviancaVuelosClient.GetEndpointAddress(EndpointConfiguration.ServicioAviancaVuelosSoapHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            ServicioAviancaVuelosSoapHttpPort,
        }
    }
}
