//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceAAAFligth
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.aa.com/types/")]
    public partial class AAException
    {
        
        private string errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.aa.com/types/")]
    public partial class Flight
    {
        
        private string cabinField;
        
        private System.Nullable<System.DateTime> arrivingDateField;
        
        private System.Nullable<double> priceField;
        
        private string arrivingCityField;
        
        private string mealsField;
        
        private System.Nullable<System.DateTime> departinDateField;
        
        private string departinCityField;
        
        private int numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string cabin
        {
            get
            {
                return this.cabinField;
            }
            set
            {
                this.cabinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> arrivingDate
        {
            get
            {
                return this.arrivingDateField;
            }
            set
            {
                this.arrivingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<double> price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string arrivingCity
        {
            get
            {
                return this.arrivingCityField;
            }
            set
            {
                this.arrivingCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string meals
        {
            get
            {
                return this.mealsField;
            }
            set
            {
                this.mealsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> departinDate
        {
            get
            {
                return this.departinDateField;
            }
            set
            {
                this.departinDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string departinCity
        {
            get
            {
                return this.departinCityField;
            }
            set
            {
                this.departinCityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.aa.com/", ConfigurationName="ServiceReferenceAAAFligth.AAFlightsService")]
    public interface AAFlightsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aa.com//bookFligth", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ServiceReferenceAAAFligth.AAException), Action="http://services.aa.com//bookFligth", Name="AAExceptionElement", Namespace="http://services.aa.com/types/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceAAAFligth.bookFligthResponse> bookFligthAsync(ServiceReferenceAAAFligth.bookFligthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.aa.com//searchFlight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceAAAFligth.searchFlightResponse> searchFlightAsync(ServiceReferenceAAAFligth.searchFlightRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bookFligthElement", WrapperNamespace="http://services.aa.com/types/", IsWrapped=true)]
    public partial class bookFligthRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aa.com/types/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceReferenceAAAFligth.Flight f;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aa.com/types/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string passengerName;
        
        public bookFligthRequest()
        {
        }
        
        public bookFligthRequest(ServiceReferenceAAAFligth.Flight f, string passengerName)
        {
            this.f = f;
            this.passengerName = passengerName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bookFligthResponseElement", WrapperNamespace="http://services.aa.com/types/", IsWrapped=true)]
    public partial class bookFligthResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aa.com/types/", Order=0)]
        public bool result;
        
        public bookFligthResponse()
        {
        }
        
        public bookFligthResponse(bool result)
        {
            this.result = result;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.aa.com/types/")]
    public partial class Trip
    {
        
        private Flight[] flightsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("flights", IsNullable=true, Order=0)]
        public Flight[] flights
        {
            get
            {
                return this.flightsField;
            }
            set
            {
                this.flightsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchFlightElement", WrapperNamespace="http://services.aa.com/types/", IsWrapped=true)]
    public partial class searchFlightRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aa.com/types/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string departinCity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aa.com/types/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string arrivingCity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aa.com/types/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> departinDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aa.com/types/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cabin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aa.com/types/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PromotionCode;
        
        public searchFlightRequest()
        {
        }
        
        public searchFlightRequest(string departinCity, string arrivingCity, System.Nullable<System.DateTime> departinDate, string cabin, string PromotionCode)
        {
            this.departinCity = departinCity;
            this.arrivingCity = arrivingCity;
            this.departinDate = departinDate;
            this.cabin = cabin;
            this.PromotionCode = PromotionCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchFlightResponseElement", WrapperNamespace="http://services.aa.com/types/", IsWrapped=true)]
    public partial class searchFlightResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.aa.com/types/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("result", IsNullable=true)]
        public ServiceReferenceAAAFligth.Trip[] result;
        
        public searchFlightResponse()
        {
        }
        
        public searchFlightResponse(ServiceReferenceAAAFligth.Trip[] result)
        {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface AAFlightsServiceChannel : ServiceReferenceAAAFligth.AAFlightsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class AAFlightsServiceClient : System.ServiceModel.ClientBase<ServiceReferenceAAAFligth.AAFlightsService>, ServiceReferenceAAAFligth.AAFlightsService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AAFlightsServiceClient() : 
                base(AAFlightsServiceClient.GetDefaultBinding(), AAFlightsServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AAFlightsServiceSoapHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AAFlightsServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AAFlightsServiceClient.GetBindingForEndpoint(endpointConfiguration), AAFlightsServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AAFlightsServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AAFlightsServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AAFlightsServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AAFlightsServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AAFlightsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceAAAFligth.bookFligthResponse> ServiceReferenceAAAFligth.AAFlightsService.bookFligthAsync(ServiceReferenceAAAFligth.bookFligthRequest request)
        {
            return base.Channel.bookFligthAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAAAFligth.bookFligthResponse> bookFligthAsync(ServiceReferenceAAAFligth.Flight f, string passengerName)
        {
            ServiceReferenceAAAFligth.bookFligthRequest inValue = new ServiceReferenceAAAFligth.bookFligthRequest();
            inValue.f = f;
            inValue.passengerName = passengerName;
            return ((ServiceReferenceAAAFligth.AAFlightsService)(this)).bookFligthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceAAAFligth.searchFlightResponse> ServiceReferenceAAAFligth.AAFlightsService.searchFlightAsync(ServiceReferenceAAAFligth.searchFlightRequest request)
        {
            return base.Channel.searchFlightAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAAAFligth.searchFlightResponse> searchFlightAsync(string departinCity, string arrivingCity, System.Nullable<System.DateTime> departinDate, string cabin, string PromotionCode)
        {
            ServiceReferenceAAAFligth.searchFlightRequest inValue = new ServiceReferenceAAAFligth.searchFlightRequest();
            inValue.departinCity = departinCity;
            inValue.arrivingCity = arrivingCity;
            inValue.departinDate = departinDate;
            inValue.cabin = cabin;
            inValue.PromotionCode = PromotionCode;
            return ((ServiceReferenceAAAFligth.AAFlightsService)(this)).searchFlightAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AAFlightsServiceSoapHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AAFlightsServiceSoapHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.100:8888/TuresBalonProviders-AA-context-root/AAFlightsServiceSoa" +
                        "pHttpPort");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AAFlightsServiceClient.GetBindingForEndpoint(EndpointConfiguration.AAFlightsServiceSoapHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AAFlightsServiceClient.GetEndpointAddress(EndpointConfiguration.AAFlightsServiceSoapHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            AAFlightsServiceSoapHttpPort,
        }
    }
}
