/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.puj.aes.calificacion.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author Johan Céspedes at PUJ
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Proveedor {

    private String idProveedor;
    private String servicio;
    private String razonSocial;
    private String nombre;
    private String email;
    private String direccion;
    private String teléfono;
    private String pais;
    private String contacto;
    private String peso;
    private String calificacion;
    private boolean estado;
    private String descripcion;

    public Proveedor(String idProveedor) {
        this.idProveedor = idProveedor;
    }
}
