//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceHiltonBooking
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomReservation", Namespace="http://services.hilton.com/types/")]
    public partial class RoomReservation : object
    {
        
        private string guestNameField;
        
        private int roomNumberField;
        
        private System.Nullable<System.DateTime> checkoutField;
        
        private string hotelField;
        
        private System.Nullable<System.DateTime> checkinField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string guestName
        {
            get
            {
                return this.guestNameField;
            }
            set
            {
                this.guestNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int roomNumber
        {
            get
            {
                return this.roomNumberField;
            }
            set
            {
                this.roomNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> checkout
        {
            get
            {
                return this.checkoutField;
            }
            set
            {
                this.checkoutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string hotel
        {
            get
            {
                return this.hotelField;
            }
            set
            {
                this.hotelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<System.DateTime> checkin
        {
            get
            {
                return this.checkinField;
            }
            set
            {
                this.checkinField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.hilton.com/", ConfigurationName="ServiceReferenceHiltonBooking.HiltonBookingService")]
    public interface HiltonBookingService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.hilton.com//bookRoom", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReferenceHiltonBooking.bookRoomResponse> bookRoomAsync(ServiceReferenceHiltonBooking.bookRoomRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bookRoomElement", WrapperNamespace="http://services.hilton.com/types/", IsWrapped=true)]
    public partial class bookRoomRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.hilton.com/types/", Order=0)]
        public ServiceReferenceHiltonBooking.RoomReservation r;
        
        public bookRoomRequest()
        {
        }
        
        public bookRoomRequest(ServiceReferenceHiltonBooking.RoomReservation r)
        {
            this.r = r;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bookRoomResponseElement", WrapperNamespace="http://services.hilton.com/types/", IsWrapped=true)]
    public partial class bookRoomResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.hilton.com/types/", Order=0)]
        public int result;
        
        public bookRoomResponse()
        {
        }
        
        public bookRoomResponse(int result)
        {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface HiltonBookingServiceChannel : ServiceReferenceHiltonBooking.HiltonBookingService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class HiltonBookingServiceClient : System.ServiceModel.ClientBase<ServiceReferenceHiltonBooking.HiltonBookingService>, ServiceReferenceHiltonBooking.HiltonBookingService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HiltonBookingServiceClient() : 
                base(HiltonBookingServiceClient.GetDefaultBinding(), HiltonBookingServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.HiltonBookingServiceSoapHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HiltonBookingServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(HiltonBookingServiceClient.GetBindingForEndpoint(endpointConfiguration), HiltonBookingServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HiltonBookingServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HiltonBookingServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HiltonBookingServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HiltonBookingServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HiltonBookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceHiltonBooking.bookRoomResponse> ServiceReferenceHiltonBooking.HiltonBookingService.bookRoomAsync(ServiceReferenceHiltonBooking.bookRoomRequest request)
        {
            return base.Channel.bookRoomAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceHiltonBooking.bookRoomResponse> bookRoomAsync(ServiceReferenceHiltonBooking.RoomReservation r)
        {
            ServiceReferenceHiltonBooking.bookRoomRequest inValue = new ServiceReferenceHiltonBooking.bookRoomRequest();
            inValue.r = r;
            return ((ServiceReferenceHiltonBooking.HiltonBookingService)(this)).bookRoomAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HiltonBookingServiceSoapHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HiltonBookingServiceSoapHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.100:8888/TuresBalonProviders-HiltonBookingService-context-root/H" +
                        "iltonBookingServiceSoapHttpPort");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HiltonBookingServiceClient.GetBindingForEndpoint(EndpointConfiguration.HiltonBookingServiceSoapHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HiltonBookingServiceClient.GetEndpointAddress(EndpointConfiguration.HiltonBookingServiceSoapHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            HiltonBookingServiceSoapHttpPort,
        }
    }
}
