/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.puj.aes.proveedor.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author Johan Céspedes at PUJ
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "proveedor")
public class Proveedor {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idProveedor;
    @DynamoDBAttribute
    private String razonSocial;
    @DynamoDBAttribute
    private String nombre;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String direccion;
    @DynamoDBAttribute
    private String teléfono;
    @DynamoDBAttribute
    private String pais;
    @DynamoDBAttribute
    private String contacto;
    @DynamoDBAttribute
    private String pesoConvenio;
    @DynamoDBAttribute
    private boolean estado;
    @DynamoDBAttribute
    private String descripcion;
    @DynamoDBAttribute
    private Categoria categoria;

    public Proveedor(String idProveedor) {
        this.idProveedor = idProveedor;
    }
}
