/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.puj.aes.proveedor.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * @author Johan Céspedes at PUJ
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "proveedor")
public class Proveedor {

    @DynamoDBHashKey(attributeName="idProveedor")
    @DynamoDBAutoGeneratedKey
    private String idProveedor;
    @DynamoDBAttribute(attributeName="servicio")
    private String servicio;
    @DynamoDBAttribute(attributeName="razonSocial")
    private String razonSocial;
    @DynamoDBAttribute(attributeName="nombre")
    private String nombre;
    @DynamoDBAttribute(attributeName="email")
    private String email;
    @DynamoDBAttribute(attributeName="direccion")
    private String direccion;
    @DynamoDBAttribute(attributeName="teléfono")
    private String teléfono;
    @DynamoDBAttribute(attributeName="pais")
    private String pais;
    @DynamoDBAttribute(attributeName="contacto")
    private String contacto;
    @DynamoDBAttribute(attributeName="peso")
    private String peso;
    @DynamoDBAttribute(attributeName="calificacion")
    private String calificacion;
    @DynamoDBAttribute(attributeName="estado")
    private boolean estado;
    @DynamoDBAttribute(attributeName="descripcion")
    private String descripcion;
    @DynamoDBAttribute(attributeName="categoria")
    private Categoria categoria;

    public Proveedor(String idProveedor) {
        this.idProveedor = idProveedor;
    }
}
