/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.puj.aes.proveedor.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.List;

/**
 * @author Johan Céspedes at PUJ
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "proveedor")
public class Proveedor implements Serializable {

    @DynamoDBHashKey(attributeName="idProvider")
    @DynamoDBAutoGeneratedKey
    private String idProvider;
    @DynamoDBAttribute(attributeName="productType")
    private String productType;
    @DynamoDBAttribute(attributeName="nameProvider")
    private String nameProvider;
    @DynamoDBAttribute(attributeName="email")
    private String email;
    @DynamoDBAttribute(attributeName="address")
    private String address;
    @DynamoDBAttribute(attributeName="phoneNumber")
    private String phoneNumber;
    @DynamoDBAttribute(attributeName="country")
    private String country;
    @DynamoDBAttribute(attributeName="contact")
    private String contact;
    @DynamoDBAttribute(attributeName="weight")
    private String weight;
    @DynamoDBAttribute(attributeName="rating")
    private String rating;
    @DynamoDBAttribute(attributeName="active")
    private boolean active;
    @DynamoDBAttribute(attributeName="description")
    private String description;
    @DynamoDBAttribute(attributeName="category")
    private Categoria category;

    public Proveedor(String idProvider) {
        this.idProvider = idProvider;
    }
}
