/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.com.puj.aes.reserva.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.Date;

/**
 * @author Johan Céspedes at PUJ
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "reserva")
public class Reserva {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String idReserva;
    @DynamoDBAttribute
    private String idCliente;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String direccion;
    @DynamoDBAttribute
    private String teléfono;
    @DynamoDBAttribute
    private String contacto;
    @DynamoDBAttribute
    private boolean estado;
    @DynamoDBAttribute
    private String ubicacion;
    @DynamoDBAttribute
    private Trasporte trasporte;
    @DynamoDBAttribute
    private Hospedaje hospedaje;
    @DynamoDBAttribute
    private Espectaculo espectaculo;


    public Reserva(String idReserva) {
        this.idReserva = idReserva;
    }

}
